//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanuaryMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_January_BatchEntities : DbContext
    {
        public DB_January_BatchEntities()
            : base("name=DB_January_BatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditTable> AuditTables { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EmpAddress> EmpAddresses { get; set; }
        public virtual DbSet<EmployeeIndia> EmployeeIndias { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeUK> EmployeeUKs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<ParentChild> ParentChilds { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        [DbFunction("DB_January_BatchEntities", "MyTableValuedFunction")]
        public virtual IQueryable<MyTableValuedFunction_Result> MyTableValuedFunction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MyTableValuedFunction_Result>("[DB_January_BatchEntities].[MyTableValuedFunction]()");
        }
    
        public virtual int sp_MyFirstSP(string address, Nullable<int> empId, string action, Nullable<int> employeeAddressID, ObjectParameter result)
        {
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var employeeAddressIDParameter = employeeAddressID.HasValue ?
                new ObjectParameter("EmployeeAddressID", employeeAddressID) :
                new ObjectParameter("EmployeeAddressID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MyFirstSP", addressParameter, empIdParameter, actionParameter, employeeAddressIDParameter, result);
        }
    
        public virtual ObjectResult<sp_MyFirstSPGet_Result> sp_MyFirstSPGet(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MyFirstSPGet_Result>("sp_MyFirstSPGet", nameParameter);
        }
    
        public virtual ObjectResult<sp_TransactionDemo_Result> sp_TransactionDemo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TransactionDemo_Result>("sp_TransactionDemo");
        }
    }
}
